[package]
name = "rls-analysis"
version = "0.1.0"
authors = ["Nick Cameron <ncameron@mozilla.com>"]

[dependencies]
rustc-serialize = "0.3"
log = "0.3"
rls-data = "0.1"
rls-span = "0.1"

[dev-dependencies]
derive-new = "0.3"
